name: Build aestest with precompiled Qt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Dependencies with Chocolatey
      shell: powershell
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
        choco install openssl -y

    - name: Install Ninja (optional)
      # Only if you plan to use Ninja with MSVC
      shell: powershell
      run: |
        choco install ninja -y

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '6.5.0'
        arch: 'win64_msvc2019_64'

    - name: Configure CMake
      shell: cmd
      run: |
        cmake -B build -G "Visual Studio 16 2019" -A x64 ^
          -DCMAKE_PREFIX_PATH="%Qt6_DIR%" ^
          -DOPENSSL_ROOT_DIR="C:\Program Files\OpenSSL-Win64" .

    - name: Build Project
      shell: cmd
      run: |
        cmake --build build --config Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: aestest-build
        path: build/Release/aestest.exe
