name: Static Build for aestest with cmkr

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Chocolatey
      shell: powershell
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12
        Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

    - name: Install Dependencies with Chocolatey
      shell: powershell
      run: |
        choco install cmake -y
        choco install ninja -y  # Ninja is commonly used with cmkr for efficient builds

    - name: Download and Extract Qt 6.5.0
      run: |
        Invoke-WebRequest -Uri https://download.qt.io/official_releases/qt/6.5/6.5.0/single/qt-everywhere-src-6.5.0.zip -OutFile qt.zip
        Expand-Archive -Path qt.zip -DestinationPath C:\Qt
        echo "Qt 6.5.0 extracted to C:\Qt"

    - name: Download cmkr
      run: |
        Invoke-WebRequest -Uri https://github.com/build-cmkr/cmkr/releases/latest/download/cmkr-windows.zip -OutFile cmkr.zip
        Expand-Archive -Path cmkr.zip -DestinationPath .
        Move-Item -Path cmkr\cmkr.exe -Destination .\cmkr.exe

    - name: Set up Visual Studio environment
      shell: cmd
      run: |
        REM Use vswhere to locate and set up Visual Studio environment for MSVC
        for /f "tokens=*" %%i in ('"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -find VC\Auxiliary\Build\vcvars64.bat') do set VCVARSPATH=%%i
        call "%VCVARSPATH%"

    - name: Configure and Generate Build Files with cmkr
      run: |
        .\cmkr.exe configure -DCMAKE_PREFIX_PATH="C:\Qt\qt-everywhere-src-6.5.0"  # Set Qt installation path for cmkr

    - name: Build Project
      run: |
        .\cmkr.exe build  # Builds the project using the cmkr-generated Ninja configuration

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: aestest-static-build
        path: build/Release/aestest.exe
