name: Build aestest with precompiled Qt (VS2022)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2022  # Use the Windows 2022 runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install vcpkg
      shell: powershell
      run: |
        git clone https://github.com/microsoft/vcpkg.git C:\vcpkg
        C:\vcpkg\bootstrap-vcpkg.bat -disableMetrics

    - name: Install OpenSSL with vcpkg
      shell: powershell
      run: |
        C:\vcpkg\vcpkg.exe install openssl:x64-windows

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '6.5.2'    # Ensure this version is available
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2022_64'

    - name: Configure CMake
      shell: cmd
      run: |
        cmake -B build -G "Visual Studio 17 2022" -A x64 ^
          -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake ^
          -DCMAKE_PREFIX_PATH="%Qt6_DIR%" ^
          -DOPENSSL_USE_STATIC_LIBS=TRUE .

    - name: Build Project
      shell: cmd
      run: |
        cmake --build build --config Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: aestest-build
        path: build\Release\aestest.exe
