name: Build aestest with precompiled Qt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install CMake
      uses: lukka/get-cmake@v2
      with:
        cmakeVersion: '3.27.6'

    - name: Download and Install OpenSSL
      shell: powershell
      run: |
        Invoke-WebRequest -Uri https://slproweb.com/download/Win64OpenSSL-3_1_1.msi -OutFile OpenSSL.msi
        Start-Process msiexec.exe -Wait -ArgumentList '/i', 'OpenSSL.msi', '/qn', 'INSTALLDIR="C:\OpenSSL"'

    - name: Verify OpenSSL Installation
      shell: powershell
      run: |
        if (Test-Path -Path "C:\OpenSSL\include\openssl") {
          Write-Host "OpenSSL headers found."
        } else {
          Write-Host "OpenSSL headers not found."
          exit 1
        }

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '6.5.0'
        arch: 'win64_msvc2022_64'

    - name: Configure CMake
      shell: cmd
      run: |
        cmake -B build -G "Visual Studio 17 2022" -A x64 ^
          -DCMAKE_PREFIX_PATH="%Qt6_DIR%" ^
          -DOPENSSL_ROOT_DIR="C:\OpenSSL" ^
          -DOPENSSL_USE_STATIC_LIBS=TRUE .

    - name: Build Project
      shell: cmd
      run: |
        cmake --build build --config Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: aestest-build
        path: build/Release/aestest.exe
